msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-10-29 12:34+0000\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File-ID: 670\n"
"Language: es_ES\n"

#: redbot/cogs/audio/core/events/dpy.py:40
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Ha intentado ejecutar el servidor Lavalink de Audio en una arquitectura no compatible. Solo estarán disponibles los comandos relacionados con la configuración."

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "I'm missing permissions in this server, Please address this as soon as possible.\\n\\nExpected Permissions:\\n"
msgstr "Me faltan permisos en este servidor. Solucione este problema lo antes posible..\\n\\nPermisos esperados:\\n"

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Enabled"
msgstr "Activado"

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Disabled"
msgstr "Desactivado"

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "No DJ role found. Disabling DJ mode."
msgstr "No se encontró ningún rol de DJ. Desactivación del modo DJ."

#: redbot/cogs/audio/core/events/dpy.py:134
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr "`{user_input}` no es un valor válido para `{command}`"

#: redbot/cogs/audio/core/events/dpy.py:142
msgid "Unable To Parse Argument"
msgstr "Incapaz de analizar el argumento"

#: redbot/cogs/audio/core/events/dpy.py:154
#: redbot/cogs/audio/core/events/dpy.py:163
msgid "Invalid Argument"
msgstr "Argumento no válido"

#: redbot/cogs/audio/core/events/dpy.py:155
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr "El argumento que dio para `{}` no es válido: esperaba un `{}`."

#: redbot/cogs/audio/core/events/dpy.py:175
msgid "Invalid Environment"
msgstr "Entorno no válido"

#: redbot/cogs/audio/core/events/dpy.py:176
msgid "Connection to Lavalink has been lost."
msgstr "Se perdió la conexión a Lavalink."

#: redbot/cogs/audio/core/events/dpy.py:184
msgid "No Player Available"
msgstr "Ningún jugador disponible"

#: redbot/cogs/audio/core/events/dpy.py:185
msgid "The bot is not connected to a voice channel."
msgstr "El bot no está conectado a un canal de voz."

#: redbot/cogs/audio/core/events/dpy.py:193
#: redbot/cogs/audio/core/events/lavalink.py:105
msgid "Unable to Get Track"
msgstr "No se puede realizar un seguimiento"

#: redbot/cogs/audio/core/events/dpy.py:194
#: redbot/cogs/audio/core/events/lavalink.py:106
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr "No puedo obtener una pista de Lavalink en este momento, inténtelo de nuevo en unos minutos."

#: redbot/cogs/audio/core/events/dpy.py:205
msgid "There was an issue communicating with Discord."
msgstr "Hubo un problema al comunicarse con Discord."

#: redbot/cogs/audio/core/events/dpy.py:206
msgid "This error has been reported to the bot owner."
msgstr "Este error se informó al propietario del bot."

#: redbot/cogs/audio/core/events/lavalink.py:96
msgid "Couldn't get a valid track."
msgstr "No se pudo obtener una pista válida."

#: redbot/cogs/audio/core/events/lavalink.py:128
msgid "Auto Play started."
msgstr "Se inició la reproducción automática."

#: redbot/cogs/audio/core/events/lavalink.py:143
msgid "Now Playing"
msgstr "Escuchando"

#: redbot/cogs/audio/core/events/lavalink.py:145
msgid "Track length: {length} | Requested by: {user}"
msgstr "Longitud de la pista: {length} | Solicitado por: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:166
msgid "Queue ended."
msgstr "La fila terminó."

#: redbot/cogs/audio/core/events/lavalink.py:211
msgid "Multiple Errors Detected"
msgstr "Varios errores detectados"

#: redbot/cogs/audio/core/events/lavalink.py:212
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Cierre del reproductor de audio debido a la detección de múltiples errores. Si esto persiste, informe al propietario del bot, ya que es posible que el engranaje de audio no esté disponible temporalmente."

#: redbot/cogs/audio/core/events/lavalink.py:226
msgid "Track Stuck"
msgstr "Pista atascada"

#: redbot/cogs/audio/core/events/lavalink.py:227
msgid "Playback of the song has stopped due to an unexcepted error.\\n{error}"
msgstr "La reproducción de la canción se detuvo debido a un error no aceptado.\\n{error}"

#: redbot/cogs/audio/core/events/lavalink.py:233
msgid "Track Error"
msgstr "Error de pista"

